In [1]:
emp=open("C:/Users/admin/Desktop/varu/Test Cases/emp12.csv",'r',encoding="cp1252")
emp

In [2]:
for x in emp:
    row=x.split(",")
    salary=int(row[5])
    print("\n Total Salary for " + row[1] + " is :" + str(salary))
    DA=salary*0.25
    print("DA is : " + str(DA))
    TZ=salary*0.15
    print(" TZ is :" + str(TZ))
    HRA=salary*0.16
    print("HRA is : " + str(HRA))
    CCA=salary*0.02
    print("CCA is : " + str(CCA))
    MA=salary*0.05
    print("MA is : "+str(MA))
    LIC=salary*0.05
    print("LIC is : " + str(LIC))
    NETSalary=DA+TZ+HRA+HRA+CCA+MA+LIC
    print("NET-Salary for " + row[1] + "is :" + str(NETSalary))
print("\n")

 Total Salary for Sheethal is :25000
DA is : 6250.0
 TZ is :3750.0
HRA is : 4000.0
CCA is : 500.0
MA is : 1250.0
LIC is : 1250.0
NET-Salary for Sheethalis :21000.0

 Total Salary for Sonu is :28000
DA is : 7000.0
 TZ is :4200.0
HRA is : 4480.0
CCA is : 560.0
MA is : 1400.0
LIC is : 1400.0
NET-Salary for Sonuis :23520.0

 Total Salary for Sandeep is :100000
DA is : 25000.0
 TZ is :15000.0
HRA is : 16000.0
CCA is : 2000.0
MA is : 5000.0
LIC is : 5000.0
NET-Salary for Sandeepis :84000.0

 Total Salary for Manoj is :65000
DA is : 16250.0
 TZ is :9750.0
HRA is : 10400.0
CCA is : 1300.0
MA is : 3250.0
LIC is : 3250.0
NET-Salary for Manojis :54600.0

 Total Salary for Prasanna is :15000
DA is : 3750.0
 TZ is :2250.0
HRA is : 2400.0
CCA is : 300.0
MA is : 750.0
LIC is : 750.0
NET-Salary for Prasannais :12600.0

 Total Salary for Priyanka is :20000
DA is : 5000.0
 TZ is :3000.0
HRA is : 3200.0
CCA is : 400.0
MA is : 1000.0
LIC is : 1000.0
NET-Salary for Priyankais :16800.0

 Total Salary for Shravanthi is :28000
DA is : 7000.0
 TZ is :4200.0
HRA is : 4480.0
CCA is : 560.0
MA is : 1400.0
LIC is : 1400.0
NET-Salary for Shravanthiis :23520.0

 Total Salary for Yamini is :19000
DA is : 4750.0
 TZ is :2850.0
HRA is : 3040.0
CCA is : 380.0
MA is : 950.0
LIC is : 950.0
NET-Salary for Yaminiis :15960.0

 Total Salary for Chaitanya is :25000
DA is : 6250.0
 TZ is :3750.0
HRA is : 4000.0
CCA is : 500.0
MA is : 1250.0
LIC is : 1250.0
NET-Salary for Chaitanyais :21000.0

 Total Salary for Leela Krishna is :26000
DA is : 6500.0
 TZ is :3900.0
HRA is : 4160.0
CCA is : 520.0
MA is : 1300.0
LIC is : 1300.0
NET-Salary for Leela Krishnais :21840.0

 Total Salary for Mahender is :60000
DA is : 15000.0
 TZ is :9000.0
HRA is : 9600.0
CCA is : 1200.0
MA is : 3000.0
LIC is : 3000.0
NET-Salary for Mahenderis :50400.0

 Total Salary for Yelishetty Shankar is :100000
DA is : 25000.0
 TZ is :15000.0
HRA is : 16000.0
CCA is : 2000.0
MA is : 5000.0
LIC is : 5000.0
NET-Salary for Yelishetty Shankaris :84000.0

 Total Salary for Swapna is :23000
DA is : 5750.0
 TZ is :3450.0
HRA is : 3680.0
CCA is : 460.0
MA is : 1150.0
LIC is : 1150.0
NET-Salary for Swapnais :19320.0

 Total Salary for Nikhil is :25000
DA is : 6250.0
 TZ is :3750.0
HRA is : 4000.0
CCA is : 500.0
MA is : 1250.0
LIC is : 1250.0
NET-Salary for Nikhilis :21000.0

 Total Salary for Sai Kumar is :30000
DA is : 7500.0
 TZ is :4500.0
HRA is : 4800.0
CCA is : 600.0
MA is : 1500.0
LIC is : 1500.0
NET-Salary for Sai Kumaris :25200.0